# Generated by Django 3.1.5 on 2021-01-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
