# Generated by Django 3.1.5 on 2021-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210106_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='zipcode',
            field=models.CharField(max_length=255),
        ),
    ]
