# Generated by Django 3.1.5 on 2021-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210106_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='release',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(),
        ),
    ]
