# Generated by Django 3.1.5 on 2021-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesession',
            name='energy_delivered',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chargesession',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
