export const AUTHENTICATE = "AUTHENTICATE";
export const DEL_USER = "DEL_USER";
export const RETRIEVE_CARS = "RETRIEVE_CARS";
export const RETRIEVE_CAR_CHARGES = "RETRIEVE_CAR_CHARGES";
export const RETRIEVE_STATIONS = "RETRIEVE_STATIONS";
export const RETRIEVE_POINTS_CHARGES = "RETRIEVE_POINTS_CHARGES";
